import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Menu from "@/components/Menu";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className=" flex gap-2 max-w-full bg-red-600">
        <div className="w-[15%] h-screen  ">
          <Menu/>
        </div>

        <div className="w-[70%] h-screen flex  justify-center">
        {children}
        </div>
        
        
        </body>
    </html>
  );
}
